=== hmrc/time-to-pay-proxy/resources/public/api/conf/1.0/schemas/generate/postGenerateResponseSchema.json
{
  "title": "A JSON Schema for TTP API.",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "quoteReference": {
      "type": "string",
      "minLength": 1,
      "maxLength": 15,
      "description": "This is the Quote reference"
    },
    "customerReference": {
      "type": "string",
      "minLength": 1,
      "maxLength": 15,
      "description": "Unique Customer reference"
    },
    "quoteType": {
      "type": "string",
      "enum": [
        "duration",
        "instalmentAmount"
      ],
      "description": "this will determine what IFS is required to calculate either duration or instalment amount"
    },
    "quoteDate": {
      "type": "string",
      "format": "date",
      "description": "This is the Quote date"
    },
    "numberOfInstalments": {
      "type": "integer",
      "description": "Number of instalments"
    },
    "totalDebtIncInt": {
      "type": "integer",
      "description": "This is the total debt plus interest for the plan"
    },
    "interestAccrued": {
      "type": "integer",
      "description": "This is the total interest accrued prior up to the quote"
    },
    "planInterest": {
      "type": "number",
      "description": "Interest accrued to the life of the plan"
    },
    "totalInterest": {
      "type": "number",
      "description": "This is the total interest accrued for the duration of the plan"
    },
    "instalments": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "debtItemChargeId": {
              "type": "string",
              "minLength": 1,
              "maxLength": 16,
              "description": "An ID which uniquely identifies a particular duty"
            },
            "dueDate": {
              "type": "string",
              "format": "date",
              "description": "Due date"
            },
            "amountDue": {
              "type": "integer",
              "description": "Amount due"
            },
            "expectedPayment": {
              "type": "integer",
              "description": "Expected payment"
            },
            "interestRate": {
              "type": "number",
              "description": "Interest rate"
            },
            "instalmentNumber": {
              "type": "integer",
              "description": "Instalment number"
            },
            "instalmentInterestAccrued": {
              "type": "integer",
              "description": "Instalment interest"
            },
            "instalmentBalance": {
              "type": "integer",
              "description": "Instalment balance"
            }
          }
        }
      ]
    },
    "collections": {
      "type": "object",
      "properties": {
        "initialCollection": {
          "type": "object",
          "properties": {
            "dueDate": {
              "type": "string",
              "format": "date",
              "description": "Due date"
            },
            "amountDue": {
              "type": "number",
              "description": "Amount due"
            }
          }
        },
        "regularCollections": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "dueDate": {
                "type": "string",
                "format": "date",
                "description": "Due date"
              },
              "amountDue": {
                "type": "number",
                "description": "Amount due"
              }
            }
          }
        }
      }
    }
  }
}

=== hmrc/time-to-pay-proxy/resources/public/api/conf/1.0/examples/generate/postGenerateResponse.json
{
  "quoteReference": "quoteRef1234",
  "customerReference": "custRef1234",
  "quoteType": "instalmentAmount",
  "quoteDate": "2021-05-13",
  "numberOfInstalments": 3,
  "totalDebtIncInt": 10,
  "interestAccrued": 10,
  "planInterest": 0.25,
  "totalInterest": 12.25,
  "instalments": [
    {
      "debtItemChargeId": "debtIChargeId1",
      "dueDate": "2021-05-13",
      "amountDue": 100,
      "expectedPayment": 100,
      "interestRate": 0.24,
      "instalmentNumber": 1,
      "instalmentInterestAccrued": 10,
      "instalmentBalance": 10
    },
    {
      "debtItemChargeId": "debtIChargeId2",
      "dueDate": "2021-05-13",
      "amountDue": 100,
      "expectedPayment": 100,
      "interestRate": 0.24,
      "instalmentNumber": 1,
      "instalmentInterestAccrued": 10,
      "instalmentBalance": 10
    },
    {
      "debtItemChargeId": "debtIChargeId3",
      "dueDate": "2021-05-13",
      "amountDue": 100,
      "expectedPayment": 100,
      "interestRate": 0.24,
      "instalmentNumber": 1,
      "instalmentInterestAccrued": 10,
      "instalmentBalance": 10,
      "interestCharge": 1.03
    }
  ],
  "collections": {
    "initialCollection": {
      "dueDate": "2022-06-18",
      "amountDue": 1000
    },
    "regularCollections": [
      {
        "dueDate": "2022-07-08",
        "amountDue": 1628.21
      },
      {
        "dueDate": "2022-08-08",
        "amountDue": 1628.21
      }
    ]
  }
}
